# Generated by Django 5.0 on 2024-01-27 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qradmin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_number', models.CharField(max_length=10, unique=True)),
                ('qr_code', models.CharField(max_length=50, unique=True)),
                ('point', models.IntegerField(blank=True, null=True)),
                ('used_on', models.DateTimeField(blank=True, null=True)),
                ('is_printed', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_disable', models.BooleanField(default=False)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='qradmin.qrbatch')),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
