# Generated by Django 5.0 on 2024-01-27 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qradmin', '0003_qrbatch_is_used_qrcode_is_used_bonduserwallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='qr_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
