# Generated by Django 5.0 on 2024-01-28 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qradmin', '0004_alter_qrcode_qr_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrbatch',
            name='is_disable',
        ),
        migrations.RemoveField(
            model_name='qrcode',
            name='is_disable',
        ),
        migrations.AddField(
            model_name='qrbatch',
            name='total_used_qr_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
