# Generated by Django 5.0 on 2024-01-29 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qradmin', '0005_remove_qrbatch_is_disable_remove_qrcode_is_disable_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BondUserWallet',
        ),
    ]
