# Generated by Django 5.0 on 2024-01-30 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qradmin', '0006_delete_bonduserwallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrbatch',
            name='amount_per_qr',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='qrbatch',
            name='total_amount',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
    ]
