# Generated by Django 5.0 on 2024-02-01 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qradmin', '0007_qrbatch_amount_per_qr_alter_qrbatch_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrbatch',
            name='is_used',
        ),
        migrations.RemoveField(
            model_name='qrbatch',
            name='total_used_qr_code',
        ),
        migrations.AlterField(
            model_name='qrbatch',
            name='amount_per_qr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='qrbatch',
            name='point_per_amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='qrbatch',
            name='point_per_qr',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='qrbatch',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='qrbatch',
            name='total_point',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='qrbatch',
            name='total_qr_code',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='point',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
