# Generated by Django 5.0 on 2024-02-08 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrapp', '0003_alter_bonduserwallet_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='transaction',
            name='total_point',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
