# Generated by Django 5.0 on 2025-05-13 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonduser',
            name='mobile',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
