# Generated by Django 5.0 on 2024-01-08 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_usertoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonduser',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
