# Generated by Django 5.0 on 2024-01-08 18:37

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_bonduser_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonduser',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to=account.models.upload_location),
        ),
    ]
