# Generated by Django 5.0 on 2024-05-09 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_systemparameter'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='allpermissions',
            unique_together={('page_group', 'act_code')},
        ),
    ]
