# Generated by Django 4.2.13 on 2024-05-21 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('account', '0013_alter_allpermissions_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bonduser',
            name='group',
        ),
        migrations.RemoveField(
            model_name='bonduser',
            name='groups',
        ),
        migrations.AddField(
            model_name='bonduser',
            name='groups',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
    ]
