# Generated by Django 5.0 on 2024-06-12 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_mainmenu_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonduser',
            name='is_app_user',
            field=models.BooleanField(default=False),
        ),
    ]
