# Generated by Django 5.0 on 2024-06-18 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_bonduser_is_app_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainmenu',
            name='code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mainmenu',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mainmenu',
            name='sequence',
            field=models.CharField(max_length=100),
        ),
    ]
