# Generated by Django 5.0 on 2025-01-22 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_finuser_expence_alter_finuser_income'),
    ]

    operations = [
        migrations.CreateModel(
            name='ITCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('apply_on', models.DateTimeField(blank=True, null=True)),
                ('interview_on', models.DateTimeField(blank=True, null=True)),
                ('response', models.TextField(blank=True, null=True)),
                ('job_role', models.CharField(blank=True, max_length=100, null=True)),
                ('is_done', models.BooleanField(default=True)),
                ('more', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
