# Generated by Django 5.0 on 2025-04-06 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(blank=True, db_index=True, max_length=128, null=True, verbose_name='type')),
                ('level', models.PositiveIntegerField(blank=True, choices=[(20, 'info'), (30, 'warning'), (10, 'debug'), (40, 'error'), (50, 'fatal')], db_index=True, default=40)),
                ('message', models.TextField()),
                ('traceback', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=500)),
                ('value', models.CharField(max_length=1000)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AllPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_name', models.CharField(max_length=100)),
                ('act_code', models.CharField(max_length=100)),
                ('page_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.mainmenu')),
            ],
            options={
                'unique_together': {('page_name', 'act_code')},
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField(blank=True, null=True)),
                ('action', models.TextField()),
                ('action_type', models.CharField(blank=True, choices=[('insert', 'Insert'), ('update', 'Update'), ('delete', 'Delete'), ('error', 'Error')], max_length=100, null=True)),
                ('ip_addr', models.CharField(default='', max_length=45)),
                ('action_on', models.DateTimeField(auto_now=True)),
                ('action_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='GroupPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_perm', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('permissions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.allpermissions')),
            ],
            options={
                'unique_together': {('group', 'permissions')},
            },
        ),
    ]
