# Generated by Django 5.0 on 2024-01-29 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('manager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField(blank=True, null=True)),
                ('action', models.TextField()),
                ('action_type', models.CharField(blank=True, choices=[('insert', 'Insert'), ('update', 'Update'), ('delete', 'Delete'), ('error', 'Error')], max_length=100, null=True)),
                ('ip_addr', models.CharField(default='', max_length=45)),
                ('action_on', models.DateTimeField(auto_now=True)),
                ('action_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
            ],
        ),
    ]
