# Generated by Django 5.0 on 2024-05-09 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_systemparameter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SystemParameter',
        ),
    ]
