# Generated by Django 4.2.13 on 2024-05-17 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('manager', '0004_delete_systemparameter'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=100)),
                ('page_code', models.CharField(max_length=100)),
                ('page_breadcrumbs', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='SystemParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=500)),
                ('value', models.CharField(max_length=1000)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AllPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_name', models.CharField(max_length=100)),
                ('act_code', models.CharField(max_length=100)),
                ('page_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.pagegroup')),
            ],
            options={
                'unique_together': {('page_group', 'act_code')},
            },
        ),
        migrations.CreateModel(
            name='GroupPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_perm', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('permissions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.allpermissions')),
            ],
            options={
                'unique_together': {('group', 'permissions')},
            },
        ),
    ]
