# Generated by Django 5.0 on 2024-05-21 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_remove_bonduser_group_remove_bonduser_groups_and_more'),
        ('manager', '0005_pagegroup_systemparameter_allpermissions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagegroup',
            name='page_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.mainmenu'),
        ),
    ]
