# Generated by Django 5.0 on 2024-05-22 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_mainmenu_code'),
        ('manager', '0006_alter_pagegroup_page_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='allpermissions',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='allpermissions',
            name='page_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.mainmenu'),
        ),
        migrations.RemoveField(
            model_name='allpermissions',
            name='page_group',
        ),
        migrations.DeleteModel(
            name='PageGroup',
        ),
    ]
