# Generated by Django 5.0 on 2024-05-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emaillog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_from', models.EmailField(max_length=254)),
                ('mail_to', models.TextField(blank=True, null=True)),
                ('mail_cc', models.TextField(blank=True, null=True)),
                ('mail_bcc', models.TextField(blank=True, null=True)),
                ('mail_subject', models.CharField(max_length=255)),
                ('mail_body', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('failed', 'Failed'), ('pending', 'Pending')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
