# Generated by Django 5.0 on 2024-05-27 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postoffice', '0002_alter_emaillog_mail_bcc_alter_emaillog_mail_cc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emaillog',
            old_name='mail_body',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='emaillog',
            old_name='mail_subject',
            new_name='subject',
        ),
        migrations.AddField(
            model_name='emaillog',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
