# Generated by Django 5.0 on 2024-05-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
    ]
