# Generated by Django 5.0 on 2024-06-04 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_commentanswars_commentanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='app.commentquestions'),
        ),
    ]
