# Generated by Django 5.0 on 2024-06-04 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_commentanswer_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentanswer',
            old_name='question',
            new_name='question_id',
        ),
    ]
