# Generated by Django 5.0 on 2024-06-04 12:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_question_commentanswer_question_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentanswer',
            name='question_id',
        ),
        migrations.AddField(
            model_name='commentanswer',
            name='questions',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='app.commentquestions'),
            preserve_default=False,
        ),
    ]
